name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees:
  - procatstler

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - crypto-tee (Core)
        - crypto-tee-vendor (Vendor Layer)
        - crypto-tee-platform (Platform Layer)
        - crypto-tee-rfc9421 (RFC 9421 Adapter)
        - Documentation
        - Build/CI
        - New component
        - Multiple components
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API method/function
        - New TEE backend support
        - Performance improvement
        - Security enhancement
        - Developer experience
        - Documentation
        - Testing/CI
        - Platform support
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Describe the problem or limitation you're facing..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "Describe how you'd like this feature to work..."
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: Show how the API would look
      render: rust
      placeholder: |
        // Example API usage
        let result = crypto_tee.new_feature().await?;

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: "Describe alternative solutions you've considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would help with my use case
        - High - Blocks my use case
        - Critical - Project depends on it
    validations:
      required: true

  - type: dropdown
    id: compatibility
    attributes:
      label: Backward Compatibility
      description: Would this be a breaking change?
      options:
        - No breaking changes
        - Minor breaking changes
        - Major breaking changes
        - New feature (no compatibility impact)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case description...
        2. Another use case...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Any thoughts on implementation details?
      placeholder: "Implementation ideas, constraints, or considerations..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: "Links to relevant specifications, similar implementations, etc..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: I have considered how this fits with CryptoTEE's goals
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: I have considered the security implications
          required: true